const initialState = {
    user: {},
    playing: [],
    myList: [],
    trends: [
        {
            id: 2,
            slug: "tvshow-2",
            title: "In the Dark",
            type: "Scripted",
            language: "English",
            year: 2009,
            contentRating: "16+",
            duration: 164,
            cover: "https://source.unsplash.com/featured/800x602",
            description: "Vestibulum ac est lacinia nisi venenatis tristique",
            source: "http://techslides.com/demos/sample-videos/small.mp4",
        },
        {
            id: 3,
            slug: "tvshow-3",
            title: "Instinct",
            type: "Adventure",
            language: "English",
            year: 2002,
            contentRating: "16+",
            duration: 137,
            cover: "https://source.unsplash.com/featured/800x603",
            description: "Vestibulum ac est lacinia nisi venenatis tristique",
            source: "http://techslides.com/demos/sample-videos/small.mp4",
        },
        {
            id: 4,
            slug: "tvshow-4",
            title: "Grand Hotel",
            type: "Comedy",
            language: "English",
            year: 2014,
            contentRating: "16+",
            duration: 163,
            cover: "https://source.unsplash.com/featured/800x604",
            description: "Vestibulum ac est lacinia nisi venenatis tristique",
            source: "http://techslides.com/demos/sample-videos/small.mp4",
        },
        {
            id: 5,
            slug: "tvshow-5",
            title: "Stargate Atlantis",
            type: "Scripted",
            language: "English",
            year: 2014,
            contentRating: "16+",
            duration: 194,
            cover: "https://source.unsplash.com/featured/800x605",
            description: "Vestibulum ac est lacinia nisi venenatis tristique",
            source: "http://techslides.com/demos/sample-videos/small.mp4",
        },
        {
            id: 6,
            slug: "tvshow-6",
            title: "Final Space",
            type: "Scripted",
            language: "English",
            year: 2017,
            contentRating: "16+",
            duration: 124,
            cover: "https://source.unsplash.com/featured/800x606",
            description: "Vestibulum ac est lacinia nisi venenatis tristique",
            source: "http://techslides.com/demos/sample-videos/small.mp4",
        },
        {
            id: 7,
            slug: "tvshow-7",
            title: "The InBetween",
            type: "Drama",
            language: "English",
            year: 2011,
            contentRating: "16+",
            duration: 179,
            cover: "https://source.unsplash.com/featured/800x607",
            description: "Vestibulum ac est lacinia nisi venenatis tristique",
            source: "http://techslides.com/demos/sample-videos/small.mp4",
        },
    ],
    originals: [
        {
            id: 8,
            slug: "tvshow-8",
            title: "Stargate Atlantis",
            type: "Action",
            language: "English",
            year: 2012,
            contentRating: "16+",
            duration: 148,
            cover: "https://source.unsplash.com/featured/800x608",
            description: "Vestibulum ac est lacinia nisi venenatis tristique",
            source: "http://techslides.com/demos/sample-videos/small.mp4",
        },
        {
            id: 9,
            slug: "tvshow-9",
            title: "Alien Highway",
            type: "Action",
            language: "English",
            year: 2019,
            contentRating: "16+",
            duration: 128,
            cover: "https://source.unsplash.com/featured/800x609",
            description: "Vestibulum ac est lacinia nisi venenatis tristique",
            source: "http://techslides.com/demos/sample-videos/small.mp4",
        },
        {
            id: 10,
            slug: "tvshow-10",
            title: "Elementary",
            type: "Animation",
            language: "English",
            year: 2011,
            contentRating: "16+",
            duration: 346,
            cover: "https://source.unsplash.com/featured/800x610",
            description: "Vestibulum ac est lacinia nisi venenatis tristique",
            source: "http://techslides.com/demos/sample-videos/small.mp4",
        },
        {
            id: 11,
            slug: "tvshow-11",
            title: "Strange Angel",
            type: "War",
            language: "English",
            year: 2015,
            contentRating: "16+",
            duration: 226,
            cover: "https://source.unsplash.com/featured/800x611",
            description: "Vestibulum ac est lacinia nisi venenatis tristique",
            source: "http://techslides.com/demos/sample-videos/small.mp4",
        },
        {
            id: 12,
            slug: "tvshow-12",
            title: "Private Eyes",
            type: "Comedy",
            language: "English",
            year: 2018,
            contentRating: "16+",
            duration: 190,
            cover: "https://source.unsplash.com/featured/800x612",
            description: "Vestibulum ac est lacinia nisi venenatis tristique",
            source: "http://techslides.com/demos/sample-videos/small.mp4",
        },
        {
            id: 13,
            slug: "tvshow-13",
            title: "NCIS: Los Angeles",
            type: "Drama",
            language: "English",
            year: 2010,
            contentRating: "16+",
            duration: 160,
            cover: "https://source.unsplash.com/featured/800x613",
            description: "Vestibulum ac est lacinia nisi venenatis tristique",
            source: "http://techslides.com/demos/sample-videos/small.mp4",
        },
    ],
};

export { initialState };
